// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void sellYourVehicleAllValidInputs2022BMWZ4()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";
        
        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'PE']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2A2 A2a");
        driver.FindElement(By.Name("pNumber")).Click();
        driver.FindElement(By.Name("pNumber")).SendKeys("111-111-1111");
        driver.FindElement(By.Name("email")).SendKeys("abc@gmail.com");
        driver.FindElement(By.Name("make")).SendKeys("Honda");
        driver.FindElement(By.Name("model")).SendKeys("Civic");
        driver.FindElement(By.Name("year")).SendKeys("2022");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("pCode")).Click();
        driver.FindElement(By.Name("pCode")).SendKeys("2A2 A2A");
        driver.FindElement(By.CssSelector("html")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.LinkText("http://www.jdpower.com/cars/2022/Honda/Civic")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.CssSelector(".title")).Text, Is.EqualTo("2022 Honda Civic"));
    }
    [Test]
    public void sellYourVehicleAllFieldsInputRequire()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.CssSelector(".col-sm-6")).Text, Is.EqualTo("First Name is required.Last Name is required.Address is required.City is required.Postal Code is required.Phone Number is required.Email is required.Vehicle make is required.Vehicle model is required.Vehicle year is required. "));
    }
    [Test]
    public void sellYourVehicleIncorrectCarModelInformationNotdisplayedJDPowerPage()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun ");
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2N2 N2N");
        driver.FindElement(By.Name("pNumber")).SendKeys("555-555-5555");
        driver.FindElement(By.Name("email")).SendKeys("abc@gmail.com");
        driver.FindElement(By.Name("make")).SendKeys("Honda");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.LinkText("http://www.jdpower.com/cars/2020/Honda/Z4")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.LinkText("http://www.jdpower.com/cars/2020/Honda/Z4")).Text, Is.EqualTo("http://www.jdpower.com/cars/2020/Honda/Z4"));
    }
    [Test]
    public void sellYourVehicleInvalidInputEmailWithoutAt()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2N2 N2N");
        driver.FindElement(By.Name("pNumber")).SendKeys("555-555-5555");
        driver.FindElement(By.Name("email")).SendKeys("abcgmail.com");
        driver.FindElement(By.Name("make")).SendKeys("BMW");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2021");
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("email")).Text, Is.EqualTo("abcgmail.com"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPhoneNumber11digits()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'PE']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2A2 A2A");
        driver.FindElement(By.Name("pNumber")).SendKeys("111-111-11111");
        driver.FindElement(By.Name("email")).Click();
        driver.FindElement(By.Name("email")).SendKeys("Mpark0719@conestogac.on.ca");
        driver.FindElement(By.Name("make")).Click();
        driver.FindElement(By.Name("make")).SendKeys("BMW");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2022");
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pNumber")).Text, Is.EqualTo("111-111-11111"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPhoneNumberWithLetter()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2A2 A2A");
        driver.FindElement(By.Name("pNumber")).Click();
        driver.FindElement(By.Name("pNumber")).SendKeys("222-222-22AB");
        driver.FindElement(By.Name("email")).Click();
        driver.FindElement(By.Name("email")).SendKeys("Mpark0719@conestogac.on.ca");
        driver.FindElement(By.Name("make")).SendKeys("Honda");
        driver.FindElement(By.Name("model")).SendKeys("Civic");
        driver.FindElement(By.Name("year")).SendKeys("2022");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector("section")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pNumber")).Text, Is.EqualTo("222-222-22AB"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPhoneNumberWithoutHyphen()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'PE']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2A2 A2A");
        driver.FindElement(By.Name("pNumber")).Click();
        driver.FindElement(By.Name("make")).Click();
        driver.FindElement(By.Name("pNumber")).Click();
        driver.FindElement(By.Name("pNumber")).SendKeys("333-3333333");
        driver.FindElement(By.Name("email")).SendKeys("Mpark0719@conestogac.on.ca");
        driver.FindElement(By.Name("make")).SendKeys("BMW");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pNumber")).Text, Is.EqualTo("333-3333333"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPostalCode6digits()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'PE']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("222 222");
        driver.FindElement(By.Name("pNumber")).SendKeys("555-555-5555");
        driver.FindElement(By.Name("email")).SendKeys("abc@gmail.com");
        driver.FindElement(By.Name("make")).SendKeys("BMW");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2021");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("pCode")).Click();
        driver.FindElement(By.CssSelector(".row:nth-child(6)")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pCode")).Text, Is.EqualTo("222 222"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPostalCodeAllLowerCase()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2a2 a2a");
        driver.FindElement(By.Name("pNumber")).Click();
        driver.FindElement(By.Name("pNumber")).SendKeys("333-333-3333");
        driver.FindElement(By.Name("email")).SendKeys("Mpark0719@conestogac.on.ca");
        driver.FindElement(By.Name("make")).SendKeys("Honda");
        driver.FindElement(By.Name("model")).SendKeys("Civic");
        driver.FindElement(By.Name("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pCode")).Text, Is.EqualTo("2a2 a2a"));
    }
    [Test]
    public void sellYourVehicleInvalidInputPostalCodeWithoutWhiteSpaceBetweenPCode()
    {
        //Arrange
        string baseURL = "http://localhost:8088/SellVehicle/";

        //Act
        driver.Navigate().GoToUrl(baseURL);
        driver.Manage().Window.Size = new System.Drawing.Size(909, 710);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Name("fName")).Click();
        driver.FindElement(By.Name("fName")).SendKeys("Minsun");
        driver.FindElement(By.Name("lName")).SendKeys("Park");
        driver.FindElement(By.Name("address")).SendKeys("108 University Avenue West");
        driver.FindElement(By.Name("city")).SendKeys("Waterloo");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'MB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NB']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NL']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'NS']")).Click();
        }
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'ON']")).Click();
        }
        driver.FindElement(By.Name("pCode")).SendKeys("2N2N2N");
        driver.FindElement(By.Name("pNumber")).SendKeys("555-555-5555");
        driver.FindElement(By.Name("email")).SendKeys("abc@gmail.com");
        driver.FindElement(By.Name("make")).SendKeys("BMW");
        driver.FindElement(By.Name("model")).SendKeys("Z4");
        driver.FindElement(By.Name("year")).SendKeys("2020");
        driver.FindElement(By.CssSelector(".btn")).Click();
        
        //Assert
        Assert.That(driver.FindElement(By.Name("pCode")).Text, Is.EqualTo("2N2N2N"));
    }
}
